### ISSUE TITLE
Object Attributes Are Ignored with `sha1.list()`

### ISSUE THREAD

**Issue by billdenney** [eddelbuettel/digest#126]
Attributes for list objects are ignored with `sha1.list()`.  The hash for `baz` and `zot` below seem like they should differ.  I haven't audited to check if this would apply more generally, but I assume that any object with differing attributes should have differing hashes.

In a more complex consideration, perhaps some level of attribute checking should be performed across objects so that if, for instance, I added an attribute to a POSIXlt object, the attribute would be considered, even though POSIXlt objects already have attributes as a component of the object itself.  (Hopefully that is clear.)

``` r
library(digest)
baz <- list(A=1)
zot <- baz
attr(zot, "abc") <- 1
sha1(baz)
#> [1] "6c3665e1d49d3cece26ee7ae3ede1b14e8e7d0b5"
sha1(zot)
#> [1] "6c3665e1d49d3cece26ee7ae3ede1b14e8e7d0b5"
```

<sup>Created on 2019-10-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

See also: #125

Tag: @ThierryO, @eddelbuettel

**Comment by eddelbuettel** [comment]
If we decide to change this I should probably run a reverse-depends check. 

Then again, most uses of the package are "probably"  `digest::digest()` rather than `digest::sha1()` but it will be prudent to check.  Which I can do with the machinery I use for Rcpp and friends.

**Comment by billdenney** [comment]
As an intermediate option here, we could add an `attributes=TRUE` default option which could be set to `FALSE` for the old behavior (showing my bias that attributes are part of the object and should be included).

**Comment by eddelbuettel** [comment]
Good point.  And we could feed the option default value with a global `options()` value, and/or possibly phase the change in.  So lots of change managment options _should we need them_.

**Comment by ThierryO** [comment]
A potential issue is that `sha1` itself adds attributes to the object. How should handle those? Especially in cases where the hash is calculcated as a hash of hashes (e.g. the hash of a list is the hash of the vector of hashes of its elements).

**Comment by ThierryO** [comment]
Looking a bit deeper on this, `sha1()` only sets some attributes and does some transformations if needed. Then the transformed object is passed to `digest()`. So if we would implement the attributes, should it be `sha1()` or `digest()` that handles them?

**Comment by eddelbuettel** [comment]
We could experiment with one, see if it works, backtrack if not ...

**Comment by ThierryO** [comment]
I had a better look at the code and must correct myself.
- `digest()` does takes attributes into account.
- `sha1()` always takes its own attributes into account.
- `sha1()` takes the original attributes into account for `integer`, `character`, `factor`, `logical`, `call` and `raw`.
- The fact that `sha1()` ignores the original attributes for the other classes is a bug.

The bug is easy to fix. Adding `attributes(y) <- attributes(x)` is sufficient. This will however alter the hashes in case attributes were set.

I suggest that we add a `version` argument to `sha1()` with `utils::packageVersion("digest")` as default. Then we can use the code below. Downside: the use will have to specify the older version to get the old hash. Benefit: we gain flexibility to make important changes that could break old hashes and still provide and easy way for the users to get the old hashes.
```
if (package_version("0.6.22.2") <= package_version(version)) {
    attributes(y) <- attributes(x)
}
```

**Comment by eddelbuettel** [comment]
Also see `R/init.R` where we already accomodate changes via options.  Could do same here:

https://github.com/eddelbuettel/digest/blob/4c91037e5ea54789c410d2b9da05747152a0ee59/R/init.R#L36-L40

**Comment by billdenney** [comment]
I am almost sure that I understand the fix, but since both of you have the idea of how to fix it, I think that me making a PR would be inefficient (i.e. many changes required to get it right).

And, as you’ll be in the same code, does it make sense to make the sha1.default modification at the same time (ergo no merge conflicts)?

**Comment by eddelbuettel** [comment]
I think you could / should startand lead a PR -- @ThierryO and I mau just chime in from the side. 
 
What I showed in the previous comment was simply a way to let a user also set overrides via `~/.Rprofile` or alike rather than in every call.  It's just a "nice to have fallback".  I think our discussed change is good and defensible.   Thoughts?

**Comment by ThierryO** [comment]
I'm working on a PR for this using the `getOption()` from @eddelbuettel
