### ISSUE TITLE
Issue with `digest` function with files on network drive

### ISSUE THREAD

**Issue by zross** [eddelbuettel/digest#13]
I'm getting an error running the `digest()` function on a file stored on a network drive from a Windows computer while no error occurs on the same file from the local drive.

So the following works perfectly and C is a local drive:

    fname <- "C:/junk/all_sites.prj"
    h2 <- digest(fname, algo="md5", file=TRUE)

With an identical file moved to a network drive I get an error:

    fname <- "X:/junk/all_sites.prj"
    h2 <- digest(fname, algo="md5", file=TRUE)
    Error in digest(fname, algo = "md5", file = TRUE) : 
      The specified file is not readable: X:/junk/all_sites.prj

This is causing problems with the `deployApp()` function in Shiny and the `document()` function in devtools but report digest errors. I [reported this](https://github.com/rstudio/shinyapps/issues/140) to RStudio (thinking it was a Shiny issue).

It seems this may be due to the `file.access` function used by `digest`. The code:

    file.access(fname, mode=4)

returns a 0 (success) using the local path and a -1 (failure) with the network path.

R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
digest_0.6.4

**Comment by eddelbuettel** [comment]
Methinks that is an OS issue.  We do nothing but opening and reading / writiing files.  We don't even know whether the file is local or not.  So in brief if this fails you may just have to work on a local file and (as needed) move it.  

The help page for `file.access` mentions to issues related to network drives, so maybe you need to sort this out at your end?

**Comment by zross** [comment]
Thanks for the quick response. As you suggest, I'll sort this out on my end.

**Comment by marcelboldt** [comment]
I have the same problem... Seems Windows related: if I call the windows method _access directly I get the same result:


```
library(inline)
inc <- "
#include <io.h>
"

src <- "
int res;
res = _access( \"d:\\path\\file.txt\" ,4);
return(wrap(res));
"

acc <- cxxfunction(signature(),
               body=src, 
               includes=inc,
               plugin="Rcpp")
acc()

# 0 for my C: drive
# -1 for -1 for a network drive (file system shown by Windows 7: CSC-Cache), currently in offline mode
```

**Comment by eddelbuettel** [comment]
Still don't think this is my issue. "Doctor it hurts when I do this ..." -- just don't place the to-be-digested files on a network drive if the OS does not fully support it.

**Comment by caerbannogwhite** [comment]
Unfortunately, there are circumstances in which it is impossible (or strongly discouraged) to move or copy the data from the network drive (ie, when working with sensible data).
Since it's still possible to read the files with any other R library, my suggestion (for MD5) here is:
```R
library(readr)
library(cli)

file_content <- read_file(file_name)
md5 <- hash_md5(file_content)
```

**Comment by tloka** [comment]
Hi @eddelbuettel,

thanks first for developing this library and all your efforts; however, unfortunately, I need to follow-up on this (although I recognize you are quite annoyed by this topic, which is there since 10 years now ...).

We just stumbled over the same issue, however, NOT using any network drives at all (though, also Windows-related). In my case, I am simply in a docker container pulling a git repo, and for some reason, the complete directory of the git repo shows `file.access=-1`, although all file access is actually working.

You stated before:

> The help page for file.access mentions no issues related to network drives [...]

While this is true, the help page also states:

> Please note that it is not a good idea to use this function to test before trying to open a file [...] It is better to wrap file open attempts in 'try'

However, this is exactly what is being done in digest, using `file.access` as a guard for reading a file, although it is well-known that it is not a reliable measure for the actual readability of a file. Therefore, the documentation of `file.access` actually recommends to not use it as such.

Following would correspond to what the `file.access` help page recommends to check for reading of a file, which would replace `file.access` at this single location, without any negative side-effects I am aware of: 
```
readable <- tryCatch({
    con <- file(object, "rb")
    close(con)
    TRUE
}, error = function(e) FALSE)

if (!readable) {
    return(.errorhandler(
        "The specified file is not readable: ",
        object,
        mode = errormode
    ))
}
```

The proposed change follows the documented R recommendations and avoids known false negatives on some Windows setups.

Alternatively (or additionally), one could wrap the actual file reading task into try-catch blocks, but I see this may come with quite some effort (although, this would be even safer on multitask systems).

I would be glad if such a change would be considered.

**Comment by eddelbuettel** [comment]
The help page for `file.access` in R 4.6.1 has no such suggestion (on my system, which is Linux -- and help pages can differ per architecture and indeed I see in the [source](https://github.com/r-devel/r-svn/blob/main/src/library/base/man/file.access.Rd) that that is the case here.  Maybe you can use that suggested function to test access before `digest()` gets called?  Otherwise it has always been a general recommendation to prefer a local disk over a network drive on Windows...

PS I also think you misread the recommendation about `try(file.open())`: it essentially describes a race condition: a change may be made to the file between trying to assert that one can access it (via `file.access()`) and the actual opening to read.  That is true in principle, and on all OSs.  `digest` has coped for twenty years though.

PPS If you want to test a properly guarded (via `.isWindows()`) test that behaves correctly on your end (something I cannot test) then I would consider that in a small and clean PR.

**Comment by tloka** [comment]
Thanks you for your prompt response, much appreciated!  
  
I am aware that the exact example given is addressing race conditions in the second sentence, but I think this is more like one example why they discourage from using the function as a pre-read check (I may be wrong, though, as I am not the one writing that documentation). 

However, I think having the results from me and other users before actually show that the function is not generally robust enough for this purpose. This may be only relevant in some edge cases, but I don't think it would really hurt to adapt this check, but in exchange it could simply provide a bit more robustness when being used in non-standard Windows setups.

I will consider to provide a suggestion in a clean PR, thanks for opening up that option (although I know, there is no guarantee this will be included in the end). 

PS: As said, I am actually not working on network drives, it's actually one folder in my docker+git system which seems to have issues with the `file.access` function. While `C:/builds/<git_dir>/file.txt` gives the wrong response (-1), `C:/builds/file.txt` (which is on the same drive) is working just fine. So I think there is simply more edge cases than just referring to network drives (it may be related to how docker interacts with the host system, though, which could in some cases behave similar to network drives in the end, but I am not 100% sure what exactly is going on here).
We are currently considering as a workaround to check `file.access` before (indirectly) calling digest, and copy the file if the result is different to the result of my suggested code snippet; however, I don't feel like this is really a good and stable solution in production-level code.

**Comment by eddelbuettel** [comment]
This always was and remains an OS-level deficiency. Or in this case possibly a `git` diffiency on the OS.

**Comment by eddelbuettel** [comment]
Also note that even in the Windows-specific example, `file.access()` is still used:

```r
#ifdef windows
d <- dir(file.path(R.home(), "bin"))
df <- dir(file.path(R.home(), "bin"), full.names = TRUE)
d[file.access(df, 0) == 0] # all exist
d[file.access(df, 1) == 0] # some are executable, some are not
d[file.access(df, 4) == 0] # hopefully all are readable
d[file.access(df, 2) == 0] # they may or may not be writable
#endif
```
